<a href="https://colab.research.google.com/github/Yogesh914/pytorch_workshop/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔥 PyTorch Workshop

## [Click Here to Sign in](https://go.wisc.edu/ststoday)

# Pytorch Fundamentals

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

## Tensors
### Creating Tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item() # get the tensor back as an int

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[1,2],
                       [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([3, 4])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6492, 0.1820, 0.5076, 0.9633],
        [0.9703, 0.4471, 0.8267, 0.7552],
        [0.5443, 0.9410, 0.9077, 0.2491]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels i.e. RGB

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Range of tensors and tensors-like

In [ ]:
torch.arange(start=0, end=1000, step=50)

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [ ]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
#float 32
float_32_tensor = torch.tensor([3.0, 2.0, 9.0],
                               dtype=None,
                               device=None, # what device is your tensor on? cuda, mps, cpu?
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 2., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 2., 9.], dtype=torch.float16)

Errors when working with tensors are usually to do with the:
* datatype
* shape
* device

In [ ]:
random_tensor

tensor([[0.6492, 0.1820, 0.5076, 0.9633],
        [0.9703, 0.4471, 0.8267, 0.7552],
        [0.5443, 0.9410, 0.9077, 0.2491]])

In [ ]:
print(f"Shape: {random_tensor.shape}")
print(f"Device: {random_tensor.device}")
print(f"Datatype: {random_tensor.dtype}")

Shape: torch.Size([3, 4])
Device: cpu
Datatype: torch.float32


### Tensor Operations

In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor = torch.tensor([[1,2,3,4,5],[1,3,4,5,5]])
tensor

tensor([[1, 2, 3, 4, 5],
        [1, 3, 4, 5, 5]])

In [ ]:
tensor.T

tensor([[1, 1],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 5]])

In [ ]:
tensor.shape, tensor.T.shape

(torch.Size([2, 5]), torch.Size([5, 2]))

### Tensor Aggregation

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.sum()

tensor(450)

In [ ]:
x.min(), x.max()

(tensor(0), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.argmax() # position of max

tensor(9)

In [ ]:
x.argmin()

tensor(0)

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors

**Reshaping** - reshape to a specific shape (has to have the same number of elements)

In [ ]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

**View** - return a view of an input tensor of certain shape but share memory with the original tensor

In [ ]:
z = x.view(1, 9) # like a deep copy
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

**Stacking** - combine multiple tensors i.e. vertically or horizontally stack them

In [ ]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0) # dim = 0 vertically, 1 is horizontally typically you can have more dims depending on the dim of your tensor
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

**Squeezing** - Removes all the 1 dimensions of a tensor

In [ ]:
x = torch.zeros(2,1,2,1,2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
torch.squeeze(x), torch.squeeze(x).size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [ ]:
torch.squeeze(x, dim=1), torch.squeeze(x, dim=1).size() # the dim checks if at that position of the dim is a 1 or not and if it is then it removes that 1 dim

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

**Unsqueeze** - add a 1 dimension to a tensor

In [ ]:
x_squeezed = torch.squeeze(x)
x_squeezed.shape

torch.Size([2, 2, 2])

In [ ]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=1) # adds a 1 dim at that dim position
x_unsqueezed.shape

torch.Size([2, 1, 2, 2])

**Permute** - return a view of the tensor with dimensions swapped in a certain way

In [ ]:
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [ ]:
x_permuted = torch.permute(x, dims=(2, 0, 1)) # takes in the index positions of the dimentions you want to swap around and in what way

x_permuted.size()

torch.Size([5, 2, 3])

In [ ]:
x

tensor([[[-0.0995, -0.3411,  1.1106, -0.2323,  1.6245],
         [-1.0326,  1.0114,  0.9150,  0.8868,  0.1811],
         [ 1.0339,  1.3157, -0.1766, -1.6390, -0.0573]],

        [[-0.4321, -0.5023,  0.5485, -0.0238,  0.3624],
         [ 1.5512,  0.6246, -1.2331,  2.3029,  0.2855],
         [-0.5001, -0.2395,  0.6557, -0.4265, -0.2624]]])

In [ ]:
x[0,0,0] = 35

In [ ]:
x_permuted[0,0,0]

tensor(35.)

In [ ]:
rgb = torch.rand(size=(224, 224, 3)) # [h , w, c]

rgb_permuted = torch.permute(rgb, dims=(2, 0, 1))
rgb_permuted.size()

torch.Size([3, 224, 224])

### Indexing Tensors

In [ ]:
x = torch.randint(11, (1, 3, 3))
x

tensor([[[9, 0, 5],
         [8, 2, 8],
         [7, 8, 5]]])

In [ ]:
x[0]

tensor([[9, 0, 5],
        [8, 2, 8],
        [7, 8, 5]])

In [ ]:
x[0][1]

tensor([8, 2, 8])

In [ ]:
x[0][1][0]

tensor(8)

In [ ]:
x[:, 0] # use ':' to target all values of a dimension

tensor([[9, 0, 5]])

In [ ]:
x[:, :, 0] # first values of each row of each matrix

tensor([[9, 8, 7]])

In [ ]:
x[:, 1, 1]

tensor([2])

In [ ]:
x[:, 2, 2]

tensor([5])

In [ ]:
x[:, :, 2]

tensor([[5, 8, 5]])

### Tensors and NumPy
* Converting data `torch.from_numpy(ndarray)`, `torch.Tensor.numpy()`

In [ ]:
nd_array = np.arange(1, 10)
tensor = torch.from_numpy(nd_array).type(torch.float32) # the dtype might not be what you want since it doesn't convert it to the default dtype of a tensor
nd_array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
tensor = torch.ones(9)
nd_tensor = tensor.numpy()

tensor, nd_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [ ]:
x = torch.rand(3, 4)
y = torch.rand(3, 4)

print(x)
print(y)
print(x == y)

tensor([[0.5714, 0.6838, 0.4356, 0.6624],
        [0.7843, 0.8305, 0.5212, 0.1361],
        [0.0831, 0.3236, 0.7123, 0.3790]])
tensor([[0.9082, 0.7416, 0.4505, 0.8607],
        [0.8041, 0.8128, 0.0368, 0.8229],
        [0.5896, 0.1719, 0.9254, 0.5301]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Setting the random seed in pytorch

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED) # only works for one method block
x = torch.rand(3, 4)


torch.manual_seed(RANDOM_SEED)
y = torch.rand(3, 4)

print(x)
print(y)
print(x == y)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Putting Tensor (and models) on and off a GPU

In [ ]:
tensor = torch.tensor([1,2,3], device=device)
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor.numpy()

array([1, 2, 3])

In [ ]:
tensor.cpu().numpy()

array([1, 2, 3])